### ISSUE TITLE
[Idea] make a changelog command

### ISSUE THREAD

**Issue by Rexogamer** [CelestialCrafter/cytrus#28]
It’d be something like this: if you did cy.changelog, the bot will respond with an embed with the changelog of the latest update.

**Comment by Rexogamer** [comment]
(also pls let meh commit directly to the main repository)

**Comment by CelestialCrafter** [comment]
o cool

**Comment by Rexogamer** [comment]
yeah it would be

**Comment by Rexogamer** [comment]
since you’re making a command right now...

**Comment by CelestialCrafter** [comment]
heh

**Comment by Rexogamer** [comment]
heh x2

**Comment by Rexogamer** [comment]
the command is in the bot available to all so I’m gonna close this
